spring.datasource.url=jdbc:postgresql://localhost:5432/student_db
spring.datasource.username=postgres
spring.datasource.password=8848abcd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://localhost:27017/alisher_rk_mongo

app.security.user=admin
app.security.password=admin123

app.security.token=SECRET123